name: react CICD initial

on:
  push:
    branches:
      -main
    pull_request:
      -main

jobs:
  build:
    runs-on: ubuntu-latest

permissions:
  actions: read
  contents: read
  security-events: write

  steps:
    name: checkout repo
    uses: actions/chckout@v3

    name: setup node js
    uses: actions/setup-node@v3
    with:
      node-version: 18
      