name: React CI/CD with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run CodeQL Security Scan
        uses: github/codeql-action/init@v3
        with:
          languages: javascript,typescript

      - name: Perform CodeQL Scan
        uses: github/codeql-action/analyze@v3

      - name: Build React App
        run: yarn build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build/

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: build/

      - name: Log in to Azure Container Registry (ACR)
        run: |
          az login --service-principal \
            -u ${{ secrets.AZURE_CLIENT_ID }} \
            -p ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}

          az acr login --name reactsampleapp1acr

      - name: Build Docker Image
        run: |
          docker build -t reactsampleapp1acr.azurecr.io/react-app:latest .

      - name: Push Docker Image to ACR
        run: |
          docker push reactsampleapp1acr.azurecr.io/react-app:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Azure
        run: |
          az login --service-principal \
            -u ${{ secrets.AZURE_CLIENT_ID }} \
            -p ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Deploy to Azure Container Instances
        run: |
          az container create \
            --resource-group react-app-rs \
            --name react-container \
            --image reactsampleapp1acr.azurecr.io/react-app:latest \
            --registry-login-server reactsampleapp1acr.azurecr.io \
            --registry-username ${{ secrets.AZURE_CLIENT_ID }} \
            --registry-password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --dns-name-label react-app \
            --ports 80 \
            --os-type Linux \
            --cpu 1 \
            --memory 2

      - name: Verify Deployment
        run: az container show --resource-group react-app-rs --name react-container --query "{IP:ipAddress.ip,Status:provisioningState}" --output table
